nucleos/NucleosUserBundle

.github/workflows/continuous-integration.yml
phpstan-baseline.neon
src/EventListener/LocaleEventSubscriber.php
src/Model/LocaleAwareInterface.php
src/Model/User.php
src/Resources/config/doctrine-mapping/User.mongodb.xml
src/Resources/config/doctrine-mapping/User.orm.xml
src/Resources/config/listeners.xml

Closes #2
Sync session timezone / locale with user defined values.

Add locale aware user data

---

.github/settings.yml

Copy shared settings from https://github.com/nucleos/.github, because sync does not work.

Copy shared setting to repo

---

README.md

Fix reference to "doctrine/mongodb-odm".

Fix reference to "doctrine/mongodb-odm"

---

composer.json

It is used for the Canonicalization

Add missing extension to composer

---

src/DependencyInjection/Configuration.php

Make resetting mail optional

---

.github/settings.yml
README.md

Update documentation links

---

docs/controller_events.rst
docs/index.rst
docs/user_manager.rst

Use syntax highlight for PHP code

---

docs/installation.rst
docs/routing.rst
src/Action/ChangePasswordAction.php
src/Action/LoggedinAction.php
src/Action/ResetAction.php
src/EventListener/ResettingListener.php
src/Form/Model/Resetting.php
src/Mailer/Mail/ResettingMail.php
src/Resources/config/routing/all.xml
src/Resources/config/routing/resetting.xml
src/Resources/translations/NucleosUserBundle.de.yml
src/Resources/translations/NucleosUserBundle.en.yml
src/Resources/views/Resetting/email.txt.twig
src/Resources/views/Security/login_content.html.twig
tests/Form/Type/ResettingFormTypeTest.php

These are hopefuly the last findings before doing the first release.

Fix fork import bugs

---

src/Resources/translations/NucleosUserBundle.de.yml
src/Resources/translations/NucleosUserBundle.en.yml
src/Resources/views/Resetting/request_content.html.twig
src/Resources/views/Security/login_content.html.twig

Add bootstrap styling to html forms

Add bootstrap styling to html forms

---

src/Resources/config/doctrine.xml
src/Resources/config/doctrine_group.xml
src/Resources/config/mailer.xml
src/Resources/config/security.xml
src/Resources/config/util.xml
src/Resources/config/validator.xml

- Services are private by default
- Register missing noop mailer service

Service fixups

---

docs/configuration_reference.rst
docs/emails.rst
docs/index.rst
docs/installation.rst
docs/migrate_from_fos.rst

Closes #13 
Explain how to migrate from FOS.

Improve documentation

---

.github/workflows/continuous-integration.yml
src/Action/ChangePasswordAction.php
src/Action/LoggedinAction.php
src/Action/LoginAction.php
src/Event/GetResponseLoginEvent.php
src/NucleosUserEvents.php
src/Resources/config/security.xml

- Add extension point to intercept login attempts 
- Add extension point to intercept logged in page

Add more extension points

---

.github/workflows/continuous-integration.yml
src/DependencyInjection/NucleosUserExtension.php

In order to extend this bundle, there should be some default aliases.

Make service aliases public

---

composer.json
phpstan-baseline.neon
src/DependencyInjection/Configuration.php
src/DependencyInjection/NucleosUserExtension.php
src/Doctrine/UserListener.php
src/EventListener/AuthenticationListener.php
src/EventListener/FlashListener.php
src/EventListener/LastLoginListener.php
src/EventListener/LocaleEventListener.php
src/EventListener/ResettingListener.php
src/Noop/Exception/NoDriverException.php
src/Noop/GroupManager.php
src/Noop/UserListener.php
src/Noop/UserManager.php
src/Resources/config/noop.xml
src/Resources/config/noop_group.xml
tests/App/AppKernel.php
tests/App/config/config.yaml
tests/DependencyInjection/NucleosUserExtensionTest.php

Decouple this bundle from doctrine orm/odm. This bundle can now run without any doctrine config.

Add noop driver to allow flex recipe

---

src/Resources/views/ChangePassword/change_password_content.html.twig
src/Resources/views/Resetting/reset_content.html.twig

Using the forms without a theme should not be useful for anyone.

Use bootstrap 3 layout as default form theme

---

phpstan-baseline.neon
phpstan.neon.dist
src/DependencyInjection/Configuration.php
tests/App/config/config.yaml
tests/DependencyInjection/ConfigurationTest.php

Make group functionality optional.

Make group config optional

---

src/Resources/translations/NucleosUserBundle.es.yml
src/Resources/translations/validators.es.yml

Adding Spanish translation to this bundle.

Adding Spanish translations

---

composer.json

Drob doctrine/mongodb-odm 1, which is not being used.

Drop doctrine/mongodb-odm 1

---

src/Form/Type/ChangePasswordFormType.php
src/Form/Type/ResettingFormType.php
src/Resources/views/ChangePassword/change_password_content.html.twig
src/Resources/views/Resetting/reset_content.html.twig

Move submit buttons to form definition

---

src/Action/LoginAction.php
src/Action/RequestResetAction.php
src/Form/Type/LoginFormType.php
src/Form/Type/RequestPasswordFormType.php
src/Resources/config/resetting.php
src/Resources/config/security.php
src/Resources/views/Resetting/request_content.html.twig
src/Resources/views/Security/login_content.html.twig

Replace remaining hardcoded forms with symfony form.

Replace hardcoded forms with symfony forms

---

phpmd.xml
phpunit.xml.dist
psalm.xml
src/DependencyInjection/NucleosUserExtension.php
src/Resources/config/storage-validation/mongodb/validation.xml
src/Resources/config/storage-validation/orm/validation.xml
src/Resources/config/validation.xml

There was a problem loading the unique constraint validators.

Fix loading driver related validations

---

src/Action/LoginAction.php

Fix passing error to login form

---

src/Event/FormEvent.php

Made FormEvent non final to be able to use it in profile bundle

Make FormEvent non-final

---

src/Action/LoginAction.php
src/Form/Type/LoginFormType.php
tests/Action/LoginActionIntegrationTest.php

Closes #188
Makes the form more reusable, e.g. when you have more then one action button.

Move buttons to action

---

src/Resources/config/routing/security.xml

Closes #226
Fixed the typo within the security.xml routing file.

Fixing typo in routing
